<a href="https://colab.research.google.com/github/Alok-Senapati/Collab-Notebooks/blob/main/pandas/Pandas%20DataFrames%20-%20Creation%2C%20Indexing%20%26%20Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Pandas***

Pandas is a library used for analysis of Structured(Tabular) data such as sheets, csv files, db tables etc. having rows and columns.

## ***Why Pandas is Required ???***

### **Excel Horror Story #1: The Gene Name Massacre**

In 2016, scientists discovered something horrifying: Microsoft Excel had been **silently corrupting gene names** in genomics research for years.

| What the scientist typed | What Excel auto-converted it to |
|---|---|
| `SEPT2` (Septin-2 protein) | **September 2** |
| `MARCH1` (Membrane protein) | **March 1** |
| `DEC1` (Deleted in cancer) | **December 1** |
| `2310009E13` (gene identifier) | **2.31E+13** (scientific notation) |

A 2020 study in *PLOS Computational Biology* found that **approximately 30% of published genomics papers** with supplementary Excel files contained corrupted gene data. The damage was so widespread that the Human Gene Nomenclature Committee actually **renamed human genes** to avoid Excel corruption (e.g., SEPT2 → SEPTIN2).

**The fix?** Researchers switched to **Python/Pandas**, where a string stays a string unless YOU explicitly convert it.

### **Excel Horror Story #2: The $6.2 Billion Copy-Paste**

In 2012, JPMorgan Chase lost **$6.2 billion** in the "London Whale" incident. The root cause? A risk model built in Excel had a **copy-paste error** in a VBA macro — the formula divided by the *sum* instead of the *average*, cutting the reported risk in half.

```
EXCEL PIPELINE:                    PANDAS PIPELINE:
┌────────────────────┐             ┌────────────────────┐
│ Manual data entry  │             │ pd.read_csv()      │
│ Copy-paste formulas│             │ Scripted transforms│
│ VBA macros         │             │ Python functions   │
│ Email spreadsheet  │             │ Git version control│
│ Hope nothing broke │             │ Automated tests    │
└────────────────────┘             └────────────────────┘
```

No one reviewed the VBA code. No version control. No automated tests. Pandas solves all of these.

<div>
    <strong>Why Pandas Solves These Problems:</strong><br>
    • <strong>Explicit data types</strong> — a string stays a string unless YOU convert it<br>
    • <strong>Reproducible scripts</strong> — run the same analysis every time, no manual steps<br>
    • <strong>Version control</strong> — Python scripts work with Git; spreadsheets don't<br>
    • <strong>Scale</strong> — Excel breaks at ~1M rows; Pandas handles millions efficiently<br>
    • <strong>Transparency</strong> — every transformation is a line of code you can inspect and test
</div>

### **The Problem: NumPy Can't Handle Real-World Tables**

NumPy is brilliant for numerical computation — but real-world data has named columns, mixed types, and needs labels.

#### ***The Solution: Everything in ONE Structure***

Pandas solves all of these problems by keeping everything in a single, labeled data structure — the **DataFrame**.


<div style="background: #F5F5F5; border-left: 5px solid #999; padding: 12px 15px; margin: 10px 0; border-radius: 4px;">
    <strong>Analogy:</strong> NumPy is a <strong>scientific calculator</strong> — powerful for math, but you have to remember which button does what. Pandas is a <strong>spreadsheet on steroids</strong> — labeled columns, mixed data types, built-in filtering, and no 1-million-row limit.
</div>

### NumPy vs Pandas: Right Tool, Right Job

| Feature | NumPy | Pandas |
|---------|-------|--------|
| **Data type** | Homogeneous (all same type) | Heterogeneous (mixed types per column) |
| **Labels** | Integer positions only | Named columns and named rows |
| **Best for** | Numerical computation, linear algebra | Tabular data, data cleaning, analysis |
| **Missing data** | No native support | Built-in `NaN` handling |
| **File I/O** | Limited (`.npy`, `.txt`) | CSV, Excel, SQL, JSON, and more |
| **Think of it as** | The engine under the hood | The car you drive |

**Key message:** NumPy and Pandas are **partners**, not competitors. Pandas uses NumPy internally for all storage and computation.

In [3]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\aloks\appdata\roaming\python\python314\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in c:\users\aloks\appdata\roaming\python\python314\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aloks\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\aloks\appdata\roaming\python\python314\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\aloks\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np

## Series

1D Array with Name and Labels (Index). Similar to a Column in Dataframe.

In [5]:
# Creating a Series from a List
series = pd.Series([1, 2, 3, 4, 5])
series  ## Pandas auto assigns integer index and name [0, 1, 2 ....]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
scores = pd.Series(
    data = [34, 57, 82, 93],
    index = ["Bob", "Alice", "Rakesh", "Sweta"],
    name = "Student Scores"
)
scores

Bob       34
Alice     57
Rakesh    82
Sweta     93
Name: Student Scores, dtype: int64

In [7]:
## Creating Series from a dictionary
monthly_sales = pd.Series(
    data = {
        "Jan": 25000,
        "Feb": 31500,
        "March": 63198
    }, name = "monthly_sales"
)
monthly_sales

Jan      25000
Feb      31500
March    63198
Name: monthly_sales, dtype: int64

In [8]:
## Series Attributes
# Every Series carries metadata about itself. Notice that `.values` returns a NumPy array — proof that Pandas is built on NumPy.

print(f"Values (NumPy array): {scores.values}")
print(f"Index:                {scores.index.tolist()}")
print(f"Name:                 {scores.name}")
print(f"Data type:            {scores.dtype}")
print(f"Shape:                {scores.shape}")
print(f"Size (# elements):    {scores.size}")
print(f"Type of .values:      {type(scores.values)}")

Values (NumPy array): [34 57 82 93]
Index:                ['Bob', 'Alice', 'Rakesh', 'Sweta']
Name:                 Student Scores
Data type:            int64
Shape:                (4,)
Size (# elements):    4
Type of .values:      <class 'numpy.ndarray'>

In [9]:
## Accessing Series Elements

# Using Labels
print("Accessing Using Labels")
print(scores[["Bob", "Rakesh", "Bob", "Sweta"]])
print(scores["Bob":"Rakesh"])  # Inclusive of Rakesh

print("Accessing Using Index")
print(scores.iloc[:2])
print(scores.iloc[0:1])
print(scores.iloc[[0, 2, 1]])
print(scores.iloc[:-1])
print(scores.iloc[::-1])

Accessing Using Labels
Bob       34
Rakesh    82
Bob       34
Sweta     93
Name: Student Scores, dtype: int64
Bob       34
Alice     57
Rakesh    82
Name: Student Scores, dtype: int64
Accessing Using Index
Bob      34
Alice    57
Name: Student Scores, dtype: int64
Bob    34
Name: Student Scores, dtype: int64
Bob       34
Rakesh    82
Alice     57
Name: Student Scores, dtype: int64
Bob       34
Alice     57
Rakesh    82
Name: Student Scores, dtype: int64
Sweta     93
Rakesh    82
Alice     57
Bob       34
Name: Student Scores, dtype: int64

In [10]:
## Series Operation - Same operations as Numpy still works but the labels/index is Preserved.
scores + 5

Bob       39
Alice     62
Rakesh    87
Sweta     98
Name: Student Scores, dtype: int64

In [11]:
# Aggregation methods — same as NumPy but with label awareness
print(f"Mean score:    {scores.mean():.1f}")
print(f"Max score:     {scores.max()}  (Who? {scores.idxmax()})")  # ← idxmax returns the LABEL
print(f"Min score:     {scores.min()}  (Who? {scores.idxmin()})")
print(f"Std deviation: {scores.std():.2f}")

Mean score:    66.5
Max score:     93  (Who? Sweta)
Min score:     34  (Who? Bob)
Std deviation: 26.39

## DataFrame

A **DataFrame** is a 2D labeled data structure — like a table or spreadsheet. Each column is a Series; all columns share the same index.

In [12]:
## Creating a DataFrame

# 1. Using dictionary
employee_data = {
    "name": ["Bob", "Alice", "Rekha", "John"],
    "age": [23, 34, 21, 44],
    "salary": [32000, 42000, 29000, 67000],
    "department": ["Engineering", "Marketing", "HR", "Engineering"]
}

employees = pd.DataFrame(
    data = employee_data
)
employees

    name  age  salary   department
0    Bob   23   32000  Engineering
1  Alice   34   42000    Marketing
2  Rekha   21   29000           HR
3   John   44   67000  Engineering

In [13]:
# 2. Using List of Lists
data = [
    ["Bob", 23, 32000, "Engineering"],
    ["Alice", 34, 42000, "Marketing"],
    ["Rekha", 21, 29000, "HR"],
    ["John", 44, 67000, "Engineering"]
]

employee_v2 = pd.DataFrame(data, columns=["name", "age", "salary", "department"])
employee_v2

    name  age  salary   department
0    Bob   23   32000  Engineering
1  Alice   34   42000    Marketing
2  Rekha   21   29000           HR
3   John   44   67000  Engineering

In [14]:
# 3. From Numpy Arrays
scores = np.array([
    [34, 52, 65],
    [76, 78, 68],
    [90, 95, 89],
    [23, 43, 36]
])

scores_df = pd.DataFrame(
    data = scores,
    columns = ["Math", "Science", "English"],
    index = ["Marie", "Jack", "Harry", "Michael"]
)
scores_df

         Math  Science  English
Marie      34       52       65
Jack       76       78       68
Harry      90       95       89
Michael    23       43       36

In [15]:
# 4. From a list of dictionaries
records = [
    {'name': 'Alice',   'age': 28, 'salary': 55000},
    {'name': 'Bob',     'age': 35, 'salary': 72000},
    {'name': 'Charlie', 'age': 42, 'salary': 68000},
    {'name': 'Diana',   'age': 31, 'salary': 61000}
]

pd.DataFrame(records)

      name  age  salary
0    Alice   28   55000
1      Bob   35   72000
2  Charlie   42   68000
3    Diana   31   61000

In [16]:
# 5. From a list of dictionaries - Missing fields (NaN)
records_with_missing_fields = [
    {'name': 'Alice',   'age': 28, 'salary': 55000},
    {'name': 'Bob',     'age': 35},
    {'name': 'Charlie', 'age': 42, 'salary': 68000},
    {'name': 'Diana',   'salary': 61000}
]

# Salary and age gets converted to float automatically as NaN is float
pd.DataFrame(records_with_missing_fields)

      name   age   salary
0    Alice  28.0  55000.0
1      Bob  35.0      NaN
2  Charlie  42.0  68000.0
3    Diana   NaN  61000.0