<a href="https://colab.research.google.com/github/Alok-Senapati/Collab-Notebooks/blob/main/pandas/Pandas%20DataFrames%20-%20Creation%2C%20Indexing%20%26%20Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Pandas***

Pandas is a library used for analysis of Structured(Tabular) data such as sheets, csv files, db tables etc. having rows and columns.

## ***Why Pandas is Required ???***

### **Excel Horror Story #1: The Gene Name Massacre**

In 2016, scientists discovered something horrifying: Microsoft Excel had been **silently corrupting gene names** in genomics research for years.

| What the scientist typed | What Excel auto-converted it to |
|---|---|
| `SEPT2` (Septin-2 protein) | **September 2** |
| `MARCH1` (Membrane protein) | **March 1** |
| `DEC1` (Deleted in cancer) | **December 1** |
| `2310009E13` (gene identifier) | **2.31E+13** (scientific notation) |

A 2020 study in *PLOS Computational Biology* found that **approximately 30% of published genomics papers** with supplementary Excel files contained corrupted gene data. The damage was so widespread that the Human Gene Nomenclature Committee actually **renamed human genes** to avoid Excel corruption (e.g., SEPT2 → SEPTIN2).

**The fix?** Researchers switched to **Python/Pandas**, where a string stays a string unless YOU explicitly convert it.

### **Excel Horror Story #2: The $6.2 Billion Copy-Paste**

In 2012, JPMorgan Chase lost **$6.2 billion** in the "London Whale" incident. The root cause? A risk model built in Excel had a **copy-paste error** in a VBA macro — the formula divided by the *sum* instead of the *average*, cutting the reported risk in half.

```
EXCEL PIPELINE:                    PANDAS PIPELINE:
┌────────────────────┐             ┌────────────────────┐
│ Manual data entry  │             │ pd.read_csv()      │
│ Copy-paste formulas│             │ Scripted transforms│
│ VBA macros         │             │ Python functions   │
│ Email spreadsheet  │             │ Git version control│
│ Hope nothing broke │             │ Automated tests    │
└────────────────────┘             └────────────────────┘
```

No one reviewed the VBA code. No version control. No automated tests. Pandas solves all of these.

<div>
    <strong>Why Pandas Solves These Problems:</strong><br>
    • <strong>Explicit data types</strong> — a string stays a string unless YOU convert it<br>
    • <strong>Reproducible scripts</strong> — run the same analysis every time, no manual steps<br>
    • <strong>Version control</strong> — Python scripts work with Git; spreadsheets don't<br>
    • <strong>Scale</strong> — Excel breaks at ~1M rows; Pandas handles millions efficiently<br>
    • <strong>Transparency</strong> — every transformation is a line of code you can inspect and test
</div>

### **The Problem: NumPy Can't Handle Real-World Tables**

NumPy is brilliant for numerical computation — but real-world data has named columns, mixed types, and needs labels.

#### ***The Solution: Everything in ONE Structure***

Pandas solves all of these problems by keeping everything in a single, labeled data structure — the **DataFrame**.


<div style="background: #F5F5F5; border-left: 5px solid #999; padding: 12px 15px; margin: 10px 0; border-radius: 4px;">
    <strong>Analogy:</strong> NumPy is a <strong>scientific calculator</strong> — powerful for math, but you have to remember which button does what. Pandas is a <strong>spreadsheet on steroids</strong> — labeled columns, mixed data types, built-in filtering, and no 1-million-row limit.
</div>

### NumPy vs Pandas: Right Tool, Right Job

| Feature | NumPy | Pandas |
|---------|-------|--------|
| **Data type** | Homogeneous (all same type) | Heterogeneous (mixed types per column) |
| **Labels** | Integer positions only | Named columns and named rows |
| **Best for** | Numerical computation, linear algebra | Tabular data, data cleaning, analysis |
| **Missing data** | No native support | Built-in `NaN` handling |
| **File I/O** | Limited (`.npy`, `.txt`) | CSV, Excel, SQL, JSON, and more |
| **Think of it as** | The engine under the hood | The car you drive |

**Key message:** NumPy and Pandas are **partners**, not competitors. Pandas uses NumPy internally for all storage and computation.

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

## Series

1D Array with Name and Labels (Index). Similar to a Column in Dataframe.

In [3]:
# Creating a Series from a List
series = pd.Series([1, 2, 3, 4, 5])
series  ## Pandas auto assigns integer index and name [0, 1, 2 ....]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
scores = pd.Series(
    data = [34, 57, 82, 93],
    index = ["Bob", "Alice", "Rakesh", "Sweta"],
    name = "Student Scores"
)
scores

Bob       34
Alice     57
Rakesh    82
Sweta     93
Name: Student Scores, dtype: int64

In [5]:
## Creating Series from a dictionary
monthly_sales = pd.Series(
    data = {
        "Jan": 25000,
        "Feb": 31500,
        "March": 63198
    }, name = "monthly_sales"
)
monthly_sales

Jan      25000
Feb      31500
March    63198
Name: monthly_sales, dtype: int64

In [6]:
## Series Attributes
# Every Series carries metadata about itself. Notice that `.values` returns a NumPy array — proof that Pandas is built on NumPy.

print(f"Values (NumPy array): {scores.values}")
print(f"Index:                {scores.index.tolist()}")
print(f"Name:                 {scores.name}")
print(f"Data type:            {scores.dtype}")
print(f"Shape:                {scores.shape}")
print(f"Size (# elements):    {scores.size}")
print(f"Type of .values:      {type(scores.values)}")

Values (NumPy array): [34 57 82 93]
Index:                ['Bob', 'Alice', 'Rakesh', 'Sweta']
Name:                 Student Scores
Data type:            int64
Shape:                (4,)
Size (# elements):    4
Type of .values:      <class 'numpy.ndarray'>

In [7]:
## Accessing Series Elements

# Using Labels
print("Accessing Using Labels")
print(scores[["Bob", "Rakesh", "Bob", "Sweta"]])
print(scores["Bob":"Rakesh"])  # Inclusive of Rakesh

print("Accessing Using Index")
print(scores.iloc[:2])
print(scores.iloc[0:1])
print(scores.iloc[[0, 2, 1]])
print(scores.iloc[:-1])
print(scores.iloc[::-1])

Accessing Using Labels
Bob       34
Rakesh    82
Bob       34
Sweta     93
Name: Student Scores, dtype: int64
Bob       34
Alice     57
Rakesh    82
Name: Student Scores, dtype: int64
Accessing Using Index
Bob      34
Alice    57
Name: Student Scores, dtype: int64
Bob    34
Name: Student Scores, dtype: int64
Bob       34
Rakesh    82
Alice     57
Name: Student Scores, dtype: int64
Bob       34
Alice     57
Rakesh    82
Name: Student Scores, dtype: int64
Sweta     93
Rakesh    82
Alice     57
Bob       34
Name: Student Scores, dtype: int64

In [8]:
## Series Operation - Same operations as Numpy still works but the labels/index is Preserved.
scores + 5

Bob       39
Alice     62
Rakesh    87
Sweta     98
Name: Student Scores, dtype: int64

In [9]:
# Aggregation methods — same as NumPy but with label awareness
print(f"Mean score:    {scores.mean():.1f}")
print(f"Max score:     {scores.max()}  (Who? {scores.idxmax()})")  # ← idxmax returns the LABEL
print(f"Min score:     {scores.min()}  (Who? {scores.idxmin()})")
print(f"Std deviation: {scores.std():.2f}")

Mean score:    66.5
Max score:     93  (Who? Sweta)
Min score:     34  (Who? Bob)
Std deviation: 26.39

## DataFrame

A **DataFrame** is a 2D labeled data structure — like a table or spreadsheet. Each column is a Series; all columns share the same index.

In [10]:
## Creating a DataFrame

# 1. Using dictionary
employee_data = {
    "name": ["Bob", "Alice", "Rekha", "John"],
    "age": [23, 34, 21, 44],
    "salary": [32000, 42000, 29000, 67000],
    "department": ["Engineering", "Marketing", "HR", "Engineering"]
}

employees = pd.DataFrame(
    data = employee_data
)
employees

    name  age  salary   department
0    Bob   23   32000  Engineering
1  Alice   34   42000    Marketing
2  Rekha   21   29000           HR
3   John   44   67000  Engineering

In [11]:
# 2. Using List of Lists
data = [
    ["Bob", 23, 32000, "Engineering"],
    ["Alice", 34, 42000, "Marketing"],
    ["Rekha", 21, 29000, "HR"],
    ["John", 44, 67000, "Engineering"]
]

employee_v2 = pd.DataFrame(data, columns=["name", "age", "salary", "department"])
employee_v2

    name  age  salary   department
0    Bob   23   32000  Engineering
1  Alice   34   42000    Marketing
2  Rekha   21   29000           HR
3   John   44   67000  Engineering

In [12]:
# 3. From Numpy Arrays
scores = np.array([
    [34, 52, 65],
    [76, 78, 68],
    [90, 95, 89],
    [23, 43, 36]
])

scores_df = pd.DataFrame(
    data = scores,
    columns = ["Math", "Science", "English"],
    index = ["Marie", "Jack", "Harry", "Michael"]
)
scores_df

         Math  Science  English
Marie      34       52       65
Jack       76       78       68
Harry      90       95       89
Michael    23       43       36

In [13]:
# 4. From a list of dictionaries
records = [
    {'name': 'Alice',   'age': 28, 'salary': 55000},
    {'name': 'Bob',     'age': 35, 'salary': 72000},
    {'name': 'Charlie', 'age': 42, 'salary': 68000},
    {'name': 'Diana',   'age': 31, 'salary': 61000}
]

pd.DataFrame(records)

      name  age  salary
0    Alice   28   55000
1      Bob   35   72000
2  Charlie   42   68000
3    Diana   31   61000

In [14]:
# 5. From a list of dictionaries - Missing fields (NaN)
records_with_missing_fields = [
    {'name': 'Alice',   'age': 28, 'salary': 55000},
    {'name': 'Bob',     'age': 35},
    {'name': 'Charlie', 'age': 42, 'salary': 68000},
    {'name': 'Diana',   'salary': 61000}
]

# Salary and age gets converted to float automatically as NaN is float
pd.DataFrame(records_with_missing_fields)

      name   age   salary
0    Alice  28.0  55000.0
1      Bob  35.0      NaN
2  Charlie  42.0  68000.0
3    Diana   NaN  61000.0

In [17]:
# 6. Reading External Data
import io

# Simulate a CSV file with Indian e-commerce data
csv_data = """order_id,customer_name,product,category,price,quantity,city
ORD001,Priya Sharma,Wireless Mouse,Electronics,899,2,Mumbai
ORD002,Rahul Verma,Python Crash Course,Books,599,1,Delhi
ORD003,Anita Desai,USB-C Hub,Electronics,1299,1,Bangalore
ORD004,Vikram Patel,Cotton T-Shirt,Clothing,499,3,Chennai
ORD005,Sneha Iyer,Desk Lamp,Home,749,1,Mumbai
ORD006,Arjun Nair,Data Science Handbook,Books,899,2,Kolkata
ORD007,Meera Joshi,Bluetooth Speaker,Electronics,1999,1,Pune
ORD008,Karan Singh,Running Shoes,Clothing,2499,1,Delhi
ORD009,Divya Rao,Notebook Set,Home,349,4,Bangalore
ORD010,Amit Gupta,Mechanical Keyboard,Electronics,3499,1,Mumbai"""

df = pd.read_csv(io.StringIO(csv_data))
df  # ← Clean HTML table with column headers

,order_id,customer_name,product,category,price,quantity,city
0,ORD001,Priya Sharma,Wireless Mouse,Electronics,899,2,Mumbai
1,ORD002,Rahul Verma,Python Crash Course,Books,599,1,Delhi
2,ORD003,Anita Desai,USB-C Hub,Electronics,1299,1,Bangalore
3,ORD004,Vikram Patel,Cotton T-Shirt,Clothing,499,3,Chennai
4,ORD005,Sneha Iyer,Desk Lamp,Home,749,1,Mumbai
5,ORD006,Arjun Nair,Data Science Handbook,Books,899,2,Kolkata
6,ORD007,Meera Joshi,Bluetooth Speaker,Electronics,1999,1,Pune
7,ORD008,Karan Singh,Running Shoes,Clothing,2499,1,Delhi
8,ORD009,Divya Rao,Notebook Set,Home,349,4,Bangalore
9,ORD010,Amit Gupta,Mechanical Keyboard,Electronics,3499,1,Mumbai

In [26]:
# Select only few columns while reading
pd.read_csv(io.StringIO(csv_data), usecols=['order_id', 'customer_name'])

  order_id customer_name
0   ORD001  Priya Sharma
1   ORD002   Rahul Verma
2   ORD003   Anita Desai
3   ORD004  Vikram Patel
4   ORD005    Sneha Iyer
5   ORD006    Arjun Nair
6   ORD007   Meera Joshi
7   ORD008   Karan Singh
8   ORD009     Divya Rao
9   ORD010    Amit Gupta

In [27]:
# Only reading first n rows
pd.read_csv(io.StringIO(csv_data), nrows=4)

,order_id,customer_name,product,category,price,quantity,city
0,ORD001,Priya Sharma,Wireless Mouse,Electronics,899,2,Mumbai
1,ORD002,Rahul Verma,Python Crash Course,Books,599,1,Delhi
2,ORD003,Anita Desai,USB-C Hub,Electronics,1299,1,Bangalore
3,ORD004,Vikram Patel,Cotton T-Shirt,Clothing,499,3,Chennai

In [30]:
# Pandas strips leading zeros from if the column contains numeric data such as PINCODE or ID
# Hence, we need to explicitly provide dtypes

csv_ids = """id,name,zip_code
001,Alice,110001
002,Bob,400001
003,Charlie,560001"""

In [31]:
# WITHOUT dtype: leading zeros are stripped, zip codes become integers
df_no_dtype = pd.read_csv(io.StringIO(csv_ids))
print("WITHOUT dtype — IDs lose leading zeros:")
print(f"  id dtype:       {df_no_dtype['id'].dtype}")
print(f"  First id value: {df_no_dtype['id'].iloc[0]}  ← '001' became 1!")
print()
df_no_dtype

WITHOUT dtype — IDs lose leading zeros:
  id dtype:       int64
  First id value: 1  ← '001' became 1!

   id     name  zip_code
0   1    Alice    110001
1   2      Bob    400001
2   3  Charlie    560001

In [32]:
# WITH dtype: values are preserved as strings
df_with_dtype = pd.read_csv(io.StringIO(csv_ids), dtype={'id': str, 'zip_code': str})
print("WITH dtype={'id': str, 'zip_code': str}:")
print(f"  id dtype:       {df_with_dtype['id'].dtype}")
print(f"  First id value: {df_with_dtype['id'].iloc[0]}  ← '001' preserved!")
df_with_dtype

WITH dtype={'id': str, 'zip_code': str}:
  id dtype:       object
  First id value: 001  ← '001' preserved!

    id     name zip_code
0  001    Alice   110001
1  002      Bob   400001
2  003  Charlie   560001

<div style="background: #EAFAF1; border-left: 5px solid #2ECC71; padding: 12px 15px; margin: 10px 0; border-radius: 4px;">
    <strong>Best Practice:</strong> ALWAYS use <code>dtype=str</code> for columns containing IDs, zip codes, phone numbers, or any code with leading zeros. Without it, Pandas silently converts them to integers and you lose data.
</div>

### DataFrame Attributes Deep Dive

Every DataFrame carries rich metadata. These seven attributes are your first toolkit for understanding any dataset.

In [15]:
# Recreate our employees DataFrame for the attributes demo
employees = pd.DataFrame({
    'name':       ['Alice', 'Bob', 'Charlie', 'Diana'],
    'age':        [28, 35, 42, 31],
    'salary':     [55000, 72000, 68000, 61000],
    'department': ['Engineering', 'Marketing', 'Engineering', 'Sales']
})

print(f"1. .shape   → {employees.shape}  ({employees.shape[0]} rows, {employees.shape[1]} columns)")
print(f"2. .columns → {employees.columns.tolist()}")
print(f"3. .index   → {employees.index.tolist()}")
print(f"4. .size    → {employees.size} total elements ({employees.shape[0]}x{employees.shape[1]})")
print(f"5. .ndim    → {employees.ndim}  (Series=1, DataFrame=2)")

1. .shape   → (4, 4)  (4 rows, 4 columns)
2. .columns → ['name', 'age', 'salary', 'department']
3. .index   → [0, 1, 2, 3]
4. .size    → 16 total elements (4x4)
5. .ndim    → 2  (Series=1, DataFrame=2)

In [16]:
employees.dtypes

name          object
age            int64
salary         int64
department    object
dtype: object

<div style="background: #EBF5FB; border-left: 5px solid #3498DB; padding: 15px; margin: 10px 0; border-radius: 4px;">
    <h3 style="margin:0 0 8px 0; color:#2C3E50;">The Five-Method Exploration Ritual</h3>
    After loading <strong>ANY</strong> dataset, <strong>ALWAYS</strong> run these 5 methods — in this order. This should become automatic muscle memory.
    <ol style="margin:8px 0 0 0;">
        <li><code>.head()</code> — First 5 rows (does the data look right?)</li>
        <li><code>.tail()</code> — Last 5 rows (any weird patterns at the end?)</li>
        <li><code>.shape</code> — How many rows and columns?</li>
        <li><code>.info()</code> — Data types + missing values (health check)</li>
        <li><code>.describe()</code> — Statistical summary (min, max, mean, quartiles)</li>
    </ol>
</div>

In [19]:
df.head()

,order_id,customer_name,product,category,price,quantity,city
0,ORD001,Priya Sharma,Wireless Mouse,Electronics,899,2,Mumbai
1,ORD002,Rahul Verma,Python Crash Course,Books,599,1,Delhi
2,ORD003,Anita Desai,USB-C Hub,Electronics,1299,1,Bangalore
3,ORD004,Vikram Patel,Cotton T-Shirt,Clothing,499,3,Chennai
4,ORD005,Sneha Iyer,Desk Lamp,Home,749,1,Mumbai

In [20]:
df.tail()

,order_id,customer_name,product,category,price,quantity,city
5,ORD006,Arjun Nair,Data Science Handbook,Books,899,2,Kolkata
6,ORD007,Meera Joshi,Bluetooth Speaker,Electronics,1999,1,Pune
7,ORD008,Karan Singh,Running Shoes,Clothing,2499,1,Delhi
8,ORD009,Divya Rao,Notebook Set,Home,349,4,Bangalore
9,ORD010,Amit Gupta,Mechanical Keyboard,Electronics,3499,1,Mumbai

In [21]:
df.shape

(10, 7)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       10 non-null     object
 1   customer_name  10 non-null     object
 2   product        10 non-null     object
 3   category       10 non-null     object
 4   price          10 non-null     int64
 5   quantity       10 non-null     int64
 6   city           10 non-null     object
dtypes: int64(2), object(5)
memory usage: 692.0+ bytes

In [23]:
df.describe()

             price  quantity
count    10.000000  10.00000
mean   1329.000000   1.70000
std    1022.850049   1.05935
min     349.000000   1.00000
25%     636.500000   1.00000
50%     899.000000   1.00000
75%    1824.000000   2.00000
max    3499.000000   4.00000

In [24]:
df.describe(include='all')

,order_id,customer_name,product,category,price,quantity,city
count,10,10,10,10,10.000000,10.00000,10
unique,10,10,10,4,NaN,NaN,6
top,ORD001,Priya Sharma,Wireless Mouse,Electronics,NaN,NaN,Mumbai
freq,1,1,1,4,NaN,NaN,3
mean,NaN,NaN,NaN,NaN,1329.000000,1.70000,NaN
std,NaN,NaN,NaN,NaN,1022.850049,1.05935,NaN
min,NaN,NaN,NaN,NaN,349.000000,1.00000,NaN
25%,NaN,NaN,NaN,NaN,636.500000,1.00000,NaN
50%,NaN,NaN,NaN,NaN,899.000000,1.00000,NaN
75%,NaN,NaN,NaN,NaN,1824.000000,2.00000,NaN
max,NaN,NaN,NaN,NaN,3499.000000,4.00000,NaN

In [33]:
# ========================================
# SESSION DATASET: Indian E-Commerce Orders
# Used for Topics 5-8 and the Mini-Project
# ========================================

orders = pd.DataFrame({
    'order_id': ['ORD001', 'ORD002', 'ORD003', 'ORD004', 'ORD005',
                 'ORD006', 'ORD007', 'ORD008', 'ORD009', 'ORD010',
                 'ORD011', 'ORD012', 'ORD013', 'ORD014', 'ORD015'],

    'customer_name': ['Priya Sharma', 'Rahul Verma', 'Anita Desai',
                      'Vikram Patel', 'Sneha Iyer', 'Arjun Nair',
                      'Meera Joshi', 'Karan Singh', 'Divya Rao',
                      'Amit Gupta', 'Priya Sharma', 'Neha Kulkarni',
                      'Rohan Mehta', 'Sneha Iyer', 'Kavita Reddy'],

    'product': ['Wireless Mouse', 'Python Crash Course', 'USB-C Hub',
                'Cotton T-Shirt', 'Desk Lamp', 'Data Science Handbook',
                'Bluetooth Speaker', 'Running Shoes', 'Notebook Set',
                'Mechanical Keyboard', 'Phone Case', 'Yoga Mat',
                'LED Monitor', 'Wall Clock', 'Backpack'],

    'category': ['Electronics', 'Books', 'Electronics', 'Clothing', 'Home',
                 'Books', 'Electronics', 'Clothing', 'Home', 'Electronics',
                 'Electronics', 'Clothing', 'Electronics', 'Home', 'Clothing'],

    'price': [899, 599, 1299, 499, 749, 899, 1999, 2499, 349, 3499,
              199, 1299, 8999, 599, 1799],

    'quantity': [2, 1, 1, 3, 1, 2, 1, 1, 4, 1,
                 2, 1, 1, 2, 1],

    'city': ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Mumbai',
             'Kolkata', 'Pune', 'Delhi', 'Bangalore', 'Mumbai',
             'Chennai', 'Bangalore', 'Delhi', 'Mumbai', 'Kolkata'],

    'order_date': ['2024-01-15', '2024-01-15', '2024-01-16', '2024-01-16',
                   '2024-01-17', '2024-01-17', '2024-01-18', '2024-01-18',
                   '2024-01-19', '2024-01-19', '2024-01-20', '2024-01-20',
                   '2024-01-21', '2024-01-21', '2024-01-22']
})

print(f"Dataset loaded: {orders.shape[0]} orders, {orders.shape[1]} columns")
print(f"Columns: {orders.columns.tolist()}")

Dataset loaded: 15 orders, 8 columns
Columns: ['order_id', 'customer_name', 'product', 'category', 'price', 'quantity', 'city', 'order_date']

### Selection of Columns and Rows

In [36]:
# Selecting Columns
# dot notation
print(type(orders.order_id)) ## Returns a Series
orders.order_id

<class 'pandas.core.series.Series'>

0     ORD001
1     ORD002
2     ORD003
3     ORD004
4     ORD005
5     ORD006
6     ORD007
7     ORD008
8     ORD009
9     ORD010
10    ORD011
11    ORD012
12    ORD013
13    ORD014
14    ORD015
Name: order_id, dtype: object

In [37]:
# Bracket Notation
print(type(orders['order_id'])) ## Returns Series
orders['order_id']

<class 'pandas.core.series.Series'>

0     ORD001
1     ORD002
2     ORD003
3     ORD004
4     ORD005
5     ORD006
6     ORD007
7     ORD008
8     ORD009
9     ORD010
10    ORD011
11    ORD012
12    ORD013
13    ORD014
14    ORD015
Name: order_id, dtype: object

In [39]:
## Selecting Multiple Columns - Double Brackets. Passing List of Columns
cols_to_select = ['order_id', 'customer_name', 'product']
print(type(orders[cols_to_select]))  ## Returns a DataFrame
print(type(orders[['order_id']]))
orders[cols_to_select]

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

   order_id  customer_name                product
0    ORD001   Priya Sharma         Wireless Mouse
1    ORD002    Rahul Verma    Python Crash Course
2    ORD003    Anita Desai              USB-C Hub
3    ORD004   Vikram Patel         Cotton T-Shirt
4    ORD005     Sneha Iyer              Desk Lamp
5    ORD006     Arjun Nair  Data Science Handbook
6    ORD007    Meera Joshi      Bluetooth Speaker
7    ORD008    Karan Singh          Running Shoes
8    ORD009      Divya Rao           Notebook Set
9    ORD010     Amit Gupta    Mechanical Keyboard
10   ORD011   Priya Sharma             Phone Case
11   ORD012  Neha Kulkarni               Yoga Mat
12   ORD013    Rohan Mehta            LED Monitor
13   ORD014     Sneha Iyer             Wall Clock
14   ORD015   Kavita Reddy               Backpack

### The Critical Difference: Single vs Double Brackets

<div style="background: #EBF5FB; border-left: 5px solid #3498DB; padding: 12px 15px; margin: 10px 0; border-radius: 4px;">
    <strong>Key Concept:</strong><br>
    <code>df['price']</code> → <strong>Series</strong> (1D, shape (15,)) — one column, no header<br>
    <code>df[['price']]</code> → <strong>DataFrame</strong> (2D, shape (15, 1)) — table with header<br><br>
    <strong>Same data, different container.</strong> This distinction matters for downstream operations like merging or exporting.
</div>

### Dot Notation Pitfalls

<div style="background: #FEF9E7; border-left: 5px solid #F39C12; padding: 12px 15px; margin: 10px 0; border-radius: 4px;">
    <strong>Warning — Three cases where dot notation FAILS:</strong><br>
    1. <strong>Spaces in column names:</strong> <code>df.order date</code> → SyntaxError<br>
    2. <strong>Name matches a method:</strong> <code>df.count</code> → returns the <code>.count()</code> METHOD, not your column!<br>
    3. <strong>Column name in a variable:</strong> <code>col = 'price'; df.col</code> → AttributeError (looks for literal column named 'col')<br><br>
    <strong>Rule:</strong> Always use bracket notation <code>df['column']</code>. Dot notation is a shortcut that can silently break.
</div>